[package]
name = "first_top"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.42", features = ["serde"] }
chrono-tz = "0.10.4"
csv = "1.4.0"
itertools = "0.14.0"
rand = "0.9.2"
serde = "1.0.228"
